
INSERT INTO company (company_id, company_name) VALUES (01, 'Adams Resources & Energy');
INSERT INTO company (company_id, company_name) VALUES (02, 'Campbell Soup Company');
INSERT INTO company (company_id, company_name) VALUES (03, 'Synnex Corporation');
INSERT INTO company (company_id, company_name) VALUES (04, 'Oge Energy Corp');
INSERT INTO company (company_id, company_name) VALUES (05, 'Allstate');
INSERT INTO company (company_id, company_name) VALUES (06, 'Patriot Coal Corporation');
INSERT INTO company (company_id, company_name) VALUES (07, 'Agco Corporation');
INSERT INTO company (company_id, company_name) VALUES (08, 'Union Pacific Corporation');
INSERT INTO company (company_id, company_name) VALUES (09, 'A.o. Smith Corporation');
INSERT INTO company (company_id, company_name) VALUES (10, 'Baxter International');
INSERT INTO company (company_id, company_name) VALUES (11, 'Reliance Steel And Aluminum');
INSERT INTO company (company_id, company_name) VALUES (12, 'Select Medical Corporation');
INSERT INTO company (company_id, company_name) VALUES (13, 'Abercrombie & Fitch Co');
INSERT INTO company (company_id, company_name) VALUES (14, 'Chevron Corp');
INSERT INTO company (company_id, company_name) VALUES (15, 'Allstate Insurance Company');
INSERT INTO company (company_id, company_name) VALUES (16, 'Carter''s');
INSERT INTO company (company_id, company_name) VALUES (17, 'Sanderson Farms');
INSERT INTO company (company_id, company_name) VALUES (18, 'Kiewit');
INSERT INTO company (company_id, company_name) VALUES (19, 'Continental Airlines');
INSERT INTO company (company_id, company_name) VALUES (20, 'Jarden Corporation');
INSERT INTO company (company_id, company_name) VALUES (21, 'Cummins Engine');
INSERT INTO company (company_id, company_name) VALUES (22, 'Capital One Financial Corporation');
INSERT INTO company (company_id, company_name) VALUES (23, 'Exxonmobil');
INSERT INTO company (company_id, company_name) VALUES (24, 'Freeport-mcmoran Copper & Gold');
INSERT INTO company (company_id, company_name) VALUES (25, 'Quiksilver');
INSERT INTO company (company_id, company_name) VALUES (26, 'Adobe Systemsorporated');
INSERT INTO company (company_id, company_name) VALUES (27, 'Levi Strauss And Co');
INSERT INTO company (company_id, company_name) VALUES (28, 'Hasbro');
INSERT INTO company (company_id, company_name) VALUES (29, 'W. R. Berkley Corporation');
INSERT INTO company (company_id, company_name) VALUES (30, 'Metlife');
INSERT INTO company (company_id, company_name) VALUES (31, 'Southern Company');
INSERT INTO company (company_id, company_name) VALUES (32, 'Targa Resources');
INSERT INTO company (company_id, company_name) VALUES (33, 'Ametek');
INSERT INTO company (company_id, company_name) VALUES (34, 'Reader''s Digest Association');
INSERT INTO company (company_id, company_name) VALUES (35, 'Directv');
INSERT INTO company (company_id, company_name) VALUES (36, 'American Tire Distributors');
INSERT INTO company (company_id, company_name) VALUES (37, 'Berry Plastics Corporation');
INSERT INTO company (company_id, company_name) VALUES (38, 'The Kroger Co');
INSERT INTO company (company_id, company_name) VALUES (39, 'Coventry Health Care');
INSERT INTO company (company_id, company_name) VALUES (40, 'Bristol Myers Squibb Company');
INSERT INTO company (company_id, company_name) VALUES (41, 'Flowers Foods');
INSERT INTO company (company_id, company_name) VALUES (42, 'Genworth Financial');
INSERT INTO company (company_id, company_name) VALUES (43, 'Nationwide Insurance Company');
INSERT INTO company (company_id, company_name) VALUES (44, 'The Scotts Miracle-gro Company');
INSERT INTO company (company_id, company_name) VALUES (45, 'Bio-rad Laboratories');
INSERT INTO company (company_id, company_name) VALUES (46, 'Teradata Corporation');
INSERT INTO company (company_id, company_name) VALUES (47, 'Constellation Brands');
INSERT INTO company (company_id, company_name) VALUES (48, 'Republic Airways Holdings');
INSERT INTO company (company_id, company_name) VALUES (49, 'Republic Services');
INSERT INTO company (company_id, company_name) VALUES (50, 'Graphic Packaging Holding Company');
INSERT INTO company (company_id, company_name) VALUES (51, 'Beckman Coulter');