use segr5300;
INSERT INTO program (program_id,program_name, program_begin_date,department_id, program_categories_id) VALUES (01, 'Mechanical Engineering', '1910-10-31', '37', 2);
INSERT INTO program (program_id,program_name, program_begin_date,department_id, program_categories_id) VALUES (02, 'Computer Science', '1981-12-16', '12', 2);
INSERT INTO program (program_id,program_name, program_begin_date,department_id, program_categories_id) VALUES (03, 'Civil and Environmental Engineering ', '1929-05-16', '06', 2);
INSERT INTO program (program_id,program_name, program_begin_date,department_id, program_categories_id) VALUES (04, 'MSBA', '1996-03-12', '05', 1);
INSERT INTO program (program_id,program_name, program_begin_date,department_id, program_categories_id) VALUES (05, 'Chemistry', '2007-10-12', '07', 2);
INSERT INTO program (program_id,program_name, program_begin_date,department_id, program_categories_id) VALUES (06, 'MSF', '1985-02-23', '26', 1);
INSERT INTO program (program_id,program_name, program_begin_date,department_id, program_categories_id) VALUES (07, 'PMBA', '2005-04-30', '05', 1);
INSERT INTO program (program_id,program_name, program_begin_date,department_id, program_categories_id) VALUES (08, 'Business 118omics', '1921-12-09', '05', 2);
INSERT INTO program (program_id,program_name, program_begin_date,department_id, program_categories_id) VALUES (09, 'Sociology', '2008-01-23', '03', 2);
INSERT INTO program (program_id,program_name, program_begin_date,department_id, program_categories_id) VALUES (10, 'Finance', '1991-03-01', '26', 2);
INSERT INTO program (program_id,program_name, program_begin_date,department_id, program_categories_id) VALUES (11, 'Business and Law', '1973-09-09', '05', 2);
INSERT INTO program (program_id,program_name, program_begin_date,department_id, program_categories_id) VALUES (12, 'Business Analytics', '1906-05-22', '05', 2);
INSERT INTO program (program_id,program_name, program_begin_date,department_id, program_categories_id) VALUES (13, 'BRMB', '2013-04-18', '05', 1);
INSERT INTO program (program_id,program_name, program_begin_date,department_id, program_categories_id) VALUES (14, 'MPAC', '1904-07-11', '01', 1);
INSERT INTO program (program_id,program_name, program_begin_date,department_id, program_categories_id) VALUES (15, 'MSBL', '1932-04-24', '05', 1);
INSERT INTO program (program_id,program_name, program_begin_date,department_id, program_categories_id) VALUES (16, 'MSBA', '1982-10-03', '05', 1);
INSERT INTO program (program_id,program_name, program_begin_date,department_id, program_categories_id) VALUES (17, 'Information System', '1988-02-01', '05', 2);
INSERT INTO program (program_id,program_name, program_begin_date,department_id, program_categories_id) VALUES (18, 'Marketing', '1961-01-13', '39', 2);
INSERT INTO program (program_id,program_name, program_begin_date,department_id, program_categories_id) VALUES (19, '118omics', '1944-02-21', '18', 2);
INSERT INTO program (program_id,program_name, program_begin_date,department_id, program_categories_id) VALUES (20, '107ory', '2005-08-01', '27', 2);
INSERT INTO program (program_id,program_name, program_begin_date,department_id, program_categories_id) VALUES (21, 'Management', '1972-04-29', '38', 2);
INSERT INTO program (program_id,program_name, program_begin_date,department_id, program_categories_id) VALUES (22, 'Mathematics', '2009-04-03', '35', 2);
INSERT INTO program (program_id,program_name, program_begin_date,department_id, program_categories_id) VALUES (23, 'International Business', '2001-09-24', '29', 2);
INSERT INTO program (program_id,program_name, program_begin_date,department_id, program_categories_id) VALUES (24, 'Psychology ', '2009-04-03', '53', 2);
INSERT INTO program (program_id,program_name, program_begin_date,department_id, program_categories_id) VALUES (25, 'Accounting', '1995-02-09', '01', 2);
INSERT INTO program (program_id,program_name, program_begin_date,department_id, program_categories_id) VALUES (26, 'Nursing', '2009-04-03', '41', 2);