INSERT INTO department (department_id, department_name) VALUES ('60','Art and Art History');
INSERT INTO department (department_id, department_name) VALUES ('01','Accounting');
INSERT INTO department (department_id, department_name) VALUES ('02','Adult Education & Training');
INSERT INTO department (department_id, department_name) VALUES ('03','Anthropology, Sociology, & Social work');
INSERT INTO department (department_id, department_name) VALUES ('04','Biology');
INSERT INTO department (department_id, department_name) VALUES ('05','Business School');
INSERT INTO department (department_id, department_name) VALUES ('06','Civil/Environmental Engineering');
INSERT INTO department (department_id, department_name) VALUES ('07','Chemistry');
INSERT INTO department (department_id, department_name) VALUES ('08','Culture and Language Bridge');
INSERT INTO department (department_id, department_name) VALUES ('09','Communication/Journalism');
INSERT INTO department (department_id, department_name) VALUES ('10','Counseling');
INSERT INTO department (department_id, department_name) VALUES ('11','Criminal Justice');
INSERT INTO department (department_id, department_name) VALUES ('12','Computer Science/Software Engineering');
INSERT INTO department (department_id, department_name) VALUES ('13','Center for the Study of Sport');
INSERT INTO department (department_id, department_name) VALUES ('14','Curriculum & Instruction');
INSERT INTO department (department_id, department_name) VALUES ('15','Digital Cultures');
INSERT INTO department (department_id, department_name) VALUES ('16','Diagnostic Ultrasound');
INSERT INTO department (department_id, department_name) VALUES ('17','Electrical/Computer Engineering');
INSERT INTO department (department_id, department_name) VALUES ('18','Economics');
INSERT INTO department (department_id, department_name) VALUES ('19','Education Administration');
INSERT INTO department (department_id, department_name) VALUES ('20','Education Leadership');
INSERT INTO department (department_id, department_name) VALUES ('21','Education Professional Development');
INSERT INTO department (department_id, department_name) VALUES ('22','General Education');
INSERT INTO department (department_id, department_name) VALUES ('23','Educating Non-Native English Speakers');
INSERT INTO department (department_id, department_name) VALUES ('24','English');
INSERT INTO department (department_id, department_name) VALUES ('25','Center for Leadership Formation');
INSERT INTO department (department_id, department_name) VALUES ('26','Finance');
INSERT INTO department (department_id, department_name) VALUES ('27','History');
INSERT INTO department (department_id, department_name) VALUES ('28','Interdisciplinary Liberal Studies');
INSERT INTO department (department_id, department_name) VALUES ('29','International Studies');
INSERT INTO department (department_id, department_name) VALUES ('30','Institute of Public Service');
INSERT INTO department (department_id, department_name) VALUES ('31','Interdisciplinary Studies');
INSERT INTO department (department_id, department_name) VALUES ('32','Kinesiology');
INSERT INTO department (department_id, department_name) VALUES ('33','Law School');
INSERT INTO department (department_id, department_name) VALUES ('34','Literacy for Diverse Learners');
INSERT INTO department (department_id, department_name) VALUES ('35','Mathematics');
INSERT INTO department (department_id, department_name) VALUES ('36','Modern Languages');
INSERT INTO department (department_id, department_name) VALUES ('37','Mechanical Engineering');
INSERT INTO department (department_id, department_name) VALUES ('38','Management');
INSERT INTO department (department_id, department_name) VALUES ('39','Marketing');
INSERT INTO department (department_id, department_name) VALUES ('40','Matteo Ricci');
INSERT INTO department (department_id, department_name) VALUES ('41','Nursing');
INSERT INTO department (department_id, department_name) VALUES ('42','Organizational Leadership-NCS');
INSERT INTO department (department_id, department_name) VALUES ('43','Performing Arts & Arts Leadership');
INSERT INTO department (department_id, department_name) VALUES ('44','Philosophy');
INSERT INTO department (department_id, department_name) VALUES ('45','Physics');
INSERT INTO department (department_id, department_name) VALUES ('46','Political Science');
INSERT INTO department (department_id, department_name) VALUES ('47','Pre-Collegiate High School Program');
INSERT INTO department (department_id, department_name) VALUES ('48','Psychology');
INSERT INTO department (department_id, department_name) VALUES ('49','Study Abroad');
INSERT INTO department (department_id, department_name) VALUES ('50','Sport Administration & Leadership');
INSERT INTO department (department_id, department_name) VALUES ('51','Student Development Administration');
INSERT INTO department (department_id, department_name) VALUES ('52','Special Education');
INSERT INTO department (department_id, department_name) VALUES ('53','School Psychology');
INSERT INTO department (department_id, department_name) VALUES ('54','School of Theology & Ministry');
INSERT INTO department (department_id, department_name) VALUES ('55','Teacher Education');
INSERT INTO department (department_id, department_name) VALUES ('56','Theology and Religious Studies');
INSERT INTO department (department_id, department_name) VALUES ('57','Teaching English to Speakers of Other Languages');
INSERT INTO department (department_id, department_name) VALUES ('58','University Core');
INSERT INTO department (department_id, department_name) VALUES ('59','Web Application & Technology Studies');
INSERT INTO department (department_id, department_name) VALUES ('59','Web Application & Technology Studies');